appName: dropwizard-java-example

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO

# the only required property is resourcePackage, for more config options see below
swagger:
  resourcePackage: dropwizard.java.example.resource